#!/usr/bin/env python
'''
*| This file is part of cony
*|
*| @package     Pysol python cli application
*| @author      <lotfio lakehal>
*| @license     MIT
*| @version     0.1.0
*| @copyright   2019 lotfio lakehal
'''
from src.core  import Input, Output, App


def main():
    inp  = Input.Input()
    out  = Output.Output()
    app  = App.App(inp, out)
    app.run()


if __name__ == '__main__':
    main()
